name: Build Ardour Release

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # To ensure tags are available

    - name: Set up latest tag
      id: get_tag
      run: |
        TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
        echo "Using tag: $TAG"
        echo "tag=$TAG" >> $GITHUB_OUTPUT
        git checkout $TAG

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential pkg-config git python3 python3-dev python3-pyqt5 python3-pyqt5.qtsvg intltool \
          libasound2-dev libatkmm-1.6-dev libaubio-dev libboost-dev libcairo2-dev libcurl4-openssl-dev \
          libdbus-1-dev libfftw3-dev libflac-dev libfluidsynth-dev libglib2.0-dev libglibmm-2.4-dev \
          libgtkmm-2.4-dev libjack-jackd2-dev liblo-dev liblrdf-dev liblilv-dev libogg-dev \
          libpango1.0-dev libsamplerate0-dev libserd-dev libsord-dev libsratom-dev libsuil-dev \
          libtag1-dev libxml2-dev lv2-dev qtbase5-dev \
          libarchive-dev libwebsockets-dev libssl-dev vamp-plugin-sdk librubberband-dev libusb-1.0-0-dev \
          makeself chrpath

    - name: Build Ardour (release)
      run: |
        ./waf configure --optimize
        ./waf

    - name: Create application binary
      run: |
        cd tools/linux_packaging
        ./build --public --strip some
        ./package --public --singlearch
        tree
        
    - name: Upload release binary
      uses: actions/upload-artifact@v4
      with:
        name: ardour-release-build
        path: |
          tools/linux_packaging/install.sh
          *.run
