name: Build Ardour Release

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # To ensure tags are available

    - name: Set up latest tag
      id: get_tag
      run: |
        TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
        echo "Using tag: $TAG"
        echo "tag=$TAG" >> $GITHUB_OUTPUT
        git checkout $TAG

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libgtkmm-2.4-dev \
          libsndfile1-dev libboost-dev libxml2-dev libsamplerate0-dev \
          liblo-dev liblrdf-dev libglibmm-2.4-dev libcairo2-dev \
          libsigc++-2.0-dev libasound2-dev libjack-jackd2-dev \
          libaubio-dev libfftw3-dev libtag1-dev libcurl4-openssl-dev \
          libarchive-dev python3 intltool pkg-config git vamp-plugin-sdk

    - name: Build Ardour (release)
      run: |
        ./waf configure --optimize
        ./waf

    - name: Upload release binary
      uses: actions/upload-artifact@v4
      with:
        name: ardour-release-build
        path: build/gtk2/ardour-*
